name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # Step 3: Install dependencies
      - run: npm ci --legacy-peer-deps

      # Step 4: Start the development server in the background
      - name: Start the development server
        run: npx nx serve crew > server.log 2>&1 &

      # Step 5: Wait for the server to be ready
      - name: Wait for the server
        run: npx wait-on http://localhost:4200 --timeout=40000

      # # Step 6: Run Cypress tests
      # - name: Run Cypress tests
      #   run: npx nx e2e crew-e2e --headless

      - name: Run Affected E2E tests
        run: npx nx affected -t e2e


      # Step 7: Stop the server
      - name: Stop the server
        if: always()
        run: pkill -f "nx serve"
